### PR TITLE
fix: add role="img" to svgs for better compatibility

### PR DESCRIPTION
**Pull request by braddialpad**
Adding `role="img"` to icons for better screenreader compatibility as shown in the following articles.

svgo was wiping this out so added a rule for it.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#svg_and_roleimg
https://www.smashingmagazine.com/2021/05/accessible-svg-patterns-comparison/#best-in-show-1

### CODE REVIEW

**Comment by francisrupert** [comment]
I'd considered that before (and have even done this before), but didn't feel it necessary given that all of our SVG icons uses `aria-hidden="true"` which prevents accessible technology from announcing it.

We don't have a prop to remove that `aria-hidden` so this might not be unnecessary. I'm not suggesting adding it as a prop, since any announcing should come from the icon's parent (e.g. `button`). It's also why I removed `aria-label` for the icon since it wouldn't be announced anyway.

There is something to be said for adding it anyway in case some screenreaders don't recognize `aria-hidden=true` — heck, at that point it probably wouldn't even recognize `role="img"`.

No harm in adding it, other than added bytes.

**Review by juliodialpad — COMMENTED** [review]
I agree with @francisrupert, If we have aria-hidden="true" we don't need any accessibility features because no screen-reader would use them. We have a lot of icons and every bit added counts.

If we want to have accessible SVG's, maybe its a good idea to remove `aria-hidden` and also add the `<title>` tag inside the svg's.

**Comment by braddialpad** [comment]
> We don't have a prop to remove that `aria-hidden` so this might not be unnecessary.

We will once you see my next PR into dialtone-vue which allows setting of label on icon 😁 . This came from a request this morning to be able to set an accessible label on the svg. It is rare to need to do this but the example we had this morning was like so:

A button that contains text and an icon, the icon is of course not read out because it's aria-hidden. They can override the text for the whole button using aria-label for the whole button, however this isn't that maintainable because now we are repeating the text that's already in the button in the aria-label. it's possible that after some future changes one could be changed but it is forgotten to update the other. Ideally it would read the text already in the content and just the icon label is set separately.

A somewhat rare case, but one they have already ran into problems with in product.

**Review by juliodialpad — APPROVED** [review]
LGTM, thanks Brad.

**Pull request merged**
