### PR TITLE
feat: add attestation-outline, empty, video-settings, call-rejected, waveform icons

### PR DESCRIPTION
**Pull request by yorbi-dp**
## Description
Added ✨ new icons ✨: attestation-outline, empty, video-settings, call-rejected and waveform.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone-icons/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.

### CODE REVIEW

**Review by braddialpad — COMMENTED** [review]
This PR looks good but I see there is also a "listen" icon marked as pending in the icons figma. This icon seems different than the current "listen" icon on dialpad.design. Is it meant to replace the existing one?

**Comment by yorbi-dp** [comment]
@braddialpad I noticed that the one on Figma has been marked as 'in progress' for quite some time now. I'll double-check to see which is the correct version and probably add it in another PR 🤔

**Review by braddialpad — APPROVED** [review]
K sounds good. This one is good to go then.

**Review by iropolo — APPROVED** [review]
Thanks for the icons, it will contribute to finish our icons migrations 👍🏼

**Pull request merged**
